apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: toyshop
  namespace: toy-store
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts
      sourceRef:
        kind: GitRepository
        name: toyshop-code
        namespace: flux-system
  values:
    image:
      frontend:
        repository: myacr.azurecr.io/frontend
        tag: v1
      backend:
        repository: myacr.azurecr.io/backend
        tag: v1
