apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: toyshop
  namespace: flux-system  # Flux watches this namespace
spec:
  releaseName: toyshop
  targetNamespace: toy-store  # this is where Helm will deploy the app
  install:
    createNamespace: true     # Flux will create the toy-store namespace if it doesn't exist
  interval: 1m
  chart:
    spec:
      chart: ./charts
      sourceRef:
        kind: GitRepository
        name: toyshop-code
        namespace: flux-system
  values:
    image:
      productService:
        repository: "ghcr.io/azure-samples/aks-store-demo/product-service"
        tag: "latest"
      orderService:
        repository: "ghcr.io/azure-samples/aks-store-demo/order-service"
        tag: "latest"
      storeFront:
        repository: "ghcr.io/azure-samples/aks-store-demo/store-front"
        tag: "latest"
